### ISSUE TITLE
Bump assertj version to 3.20.2

### ISSUE THREAD

**Issue by fjakop** [camunda/camunda-bpm-assert#149]
I'm using camunda-bpm-assert in a project which manages dependency version of assertj to 3.20.2. Since the latest versions of camunda-bpm-assert are compiled against assertj 3.18.1 I get a
    
    java.lang.NoSuchMethodError: 'org.assertj.core.api.ListAssert org.assertj.core.api.ListAssert.contains(java.lang.Object[])'
	at org.camunda.bpm.engine.test.assertions.bpmn.ProcessInstanceAssert.isWaitingAt(ProcessInstanceAssert.java:147)
	at org.camunda.bpm.engine.test.assertions.bpmn.ProcessInstanceAssert.isWaitingAt(ProcessInstanceAssert.java:84)

This will be fixed using assertj version to 3.20.2 in camunda-bpm-assert.

**Comment by fjakop** [comment]
Coming back to the issue above, when is the next release expected?

**Comment by mboskamp** [comment]
Hi @fjakop,
we expect to release a new version at the latest together with 7.16.0 of the Camunda Platform which will happen on October 12th.
If there are bigger changes to Camunda Assert before we might schedule a release prior to the platform release.

**Comment by tmetzke** [comment]
@fjakop, @mboskamp,

as far as I can see in the release notes, using 3.19.0 should already fix this.
I also tested it successfully with 3.19.0 and examples using 3.30.2.

**Why is this important?**
We want to release artifacts that are compatible with what our Camunda Spring Boot Starter uses. We rely on what Spring Boot brings along here. Since Spring Boot 2.5.x brings AssertJ 3.19.0 and using 3.19.0 fixes this, I will also adjust the version to 3.19.0 here in Assert.

Let me know if you have any concerns.

Best,
Tobias

**Comment by b-olsen** [comment]
Hi, any news about release planning? Thanks in advance.

**Comment by mboskamp** [comment]
Hey @b-olsen,
We released versions 12.0.0 (with AssertJ 3.19) and 13.0,0 (with AssertJ 3.20.2) both compatible with Camunda Platform 7.16 in October 2021. See the [compatibility table](https://docs.camunda.org/manual/latest/user-guide/testing/#assertions-version-compatibility) for more information.
