### ISSUE TITLE
Test and document CmmnAwareTests

### ISSUE THREAD

**Issue by malteser** [camunda/camunda-bpm-assert#64]
Most methods there simply delegate to other classes. Can be tested and documented in one issue.

**Comment by malteser** [comment]
@martinschimak 

to test or not to test:

    public static CaseDefinitionQuery caseDefinitionQuery() {
      return repositoryService().createCaseDefinitionQuery();
    }

I'd say no, because it contains no logic and is not expected to break easily.

**Comment by martinschimak** [comment]
We actually did explicitely test such methods so far - see ProcessEngineTestsTest. But as a tendency it can easily become overkill, I agree. Many of those methods are probably better implicitely tested - in case anybody breaks them, 10+ related tests immediately break. However, in case it's a method we don't use internally but just the end user uses it, I'd prefer to have a simple test, because otherwise it can e.g. be removed by accident etc. Then we would change the public API without knowing it.

**Comment by martinschimak** [comment]
I think we can close this? Please reopen this issue if you think we still need more work here.
