### ISSUE TITLE
[CMMN] Do we need a separate descendantCaseExecution?

### ISSUE THREAD

**Issue by martinschimak** [camunda/camunda-bpm-assert#72]
We currently have two internal lookup methods to retrieve `CaseExecution` (or currently `CaseExecutionAssert`) objects "chained inside" other `CaseExecution` objects. 

I am not yet sure, whether we really need both of them. My current tendency is that it is good enough to look up all "descendant" caseExecution objects by default.

Therefore I'd vote to change the current impl in the following way:
1. `caseExecution` does retrieve all "descendant" instances rather than "child" instances.
2. We remove the `descendantCaseExecution` lookup for now

I'd also think that this is closer to the BPMN implementation we currently have. E.g. a "chained" task may live directly inside a process instance, but also live inside a subprocess of that process instance.

If we then **later discover** (or already know?) that we also need to lookup the direct child on a regular basis, I'd rather introduce a `childCaseExecution` for that. 

Arguments or opinions?

**Comment by malteser** [comment]
Just FYI, my initial reasoning was that didn't want to assert through the hierarchy of a case just to get a task whose ID I know.

Currently, my most often written line of test code looks like this:
`assertThat(caseInstance).stage(STAGE_ID).humanTask(TASK_ID).isActive()`

Whereby the `.stage(STAGE_ID)` does not add value, because the lookup is done by the item's ID, which is unique throughout the entire case instance.

But if I should write `stage(..).humanTask(..)` then I expect that task to be inside that stage.

All of this is matches the proposed behaviour. 

So we should rewrite that single caseExecution method, drop that descendent one and - more importantly - fix documentation accordingly.

**Comment by tmetzke** [comment]
Hey guys,

thanks for opening this discussion.

However, we will not work on CMMN features any time soon.
We encourage anyone to make a code contribution by submitting a pull request for this if it is a pressing concern.

Closing this as Won't Fix for now.
Feel free to open again or file a new issue in the [Issue tracker](https://app.camunda.com/jira/browse/CAM/component/14065).

Thank you for your understanding.

Best,
Tobias
