### ISSUE TITLE
[CMMN] StageAssert: filter stages only

### ISSUE THREAD

**Issue by berndruecker** [camunda/camunda-bpm-assert#87]
Currently doing
  assertThat(caseInstance).stage()

retrieves all sub executions, not only stages. The query is wrong here:
https://github.com/camunda/camunda-bpm-assert/blob/cmmn_assertions/camunda-bpm-assert/src/main/java/org/camunda/bpm/engine/test/assertions/cmmn/AbstractCaseAssert.java#L578

**Comment by malteser** [comment]
Hi Bernd,

indeed, it doesn't work. 

Currently, looking up stages is not yet supported.
Also. please note that #82 is a different thing. Its about making assertions on a stage already at hand. And it has not been contributed yet.

In the [CMMN User Guide](https://github.com/camunda/camunda-bpm-assert/blob/cmmn_assertions/camunda-bpm-assert/User_Guide_CMMN.md) we documented all supported functions.

**Comment by tmetzke** [comment]
Hi,

we removed all no-argument methods for retrieving specific case executions because the `CaseExecutionQuery` currently doesn't allow to add a condition for the activity type. Thus, we will at least always retrieve the `casePlanModel` activity and the specific descendant activity we try to retrieve by calling "stage()", "milestone()" or the likes. So, an extension of the `CaseExecutionQuery` would probably have to be implemented first.

However, we will not work on CMMN features any time soon.
We encourage anyone to make a code contribution by submitting a pull request for this if it is a pressing concern.

Closing this as Won't Fix for now.
Feel free to open again or file a new issue in the [Issue tracker](https://app.camunda.com/jira/browse/CAM/component/14065).

Thank you for your understanding.

Best,
Tobias
